eureka:
  client:
    serviceUrl:
      defaultZone: ${EUREKA_URI:http://host.docker.internal:8761/eureka}
  instance:
    preferIpAddress: true

spring:
  application:
    name: like-service
  data:

    mongodb:
      host: host.docker.internal
      database: like_db
      port: 27017
  cloud:
    discovery:
      enabled: true
server:
  port: 3020
management:
  endpoints:
    web:
      exposure:
        include: '*'





